// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtjRkaBKLaGLOQsZLbR40BahcTUilwoX0',
    appId: '1:1080283537133:web:0f40a01d2396045abab6e4',
    messagingSenderId: '1080283537133',
    projectId: 'cas-elms-new-data',
    authDomain: 'cas-elms-new-data.firebaseapp.com',
    storageBucket: 'cas-elms-new-data.firebasestorage.app',
    measurementId: 'G-VX21BHDHYD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkiQ-Aio6DqRZVh8adc8HLC9FZZebRfuc',
    appId: '1:1080283537133:android:8ed90c67a8b135f2bab6e4',
    messagingSenderId: '1080283537133',
    projectId: 'cas-elms-new-data',
    storageBucket: 'cas-elms-new-data.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxvZ1F6US3E2ncLbb6lyXdJQuaCHyrOp4',
    appId: '1:1080283537133:ios:70c934dacea2a680bab6e4',
    messagingSenderId: '1080283537133',
    projectId: 'cas-elms-new-data',
    storageBucket: 'cas-elms-new-data.firebasestorage.app',
    iosBundleId: 'com.example.flutterCasAppMain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxvZ1F6US3E2ncLbb6lyXdJQuaCHyrOp4',
    appId: '1:1080283537133:ios:70c934dacea2a680bab6e4',
    messagingSenderId: '1080283537133',
    projectId: 'cas-elms-new-data',
    storageBucket: 'cas-elms-new-data.firebasestorage.app',
    iosBundleId: 'com.example.flutterCasAppMain',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtjRkaBKLaGLOQsZLbR40BahcTUilwoX0',
    appId: '1:1080283537133:web:f42213179d7c7ac7bab6e4',
    messagingSenderId: '1080283537133',
    projectId: 'cas-elms-new-data',
    authDomain: 'cas-elms-new-data.firebaseapp.com',
    storageBucket: 'cas-elms-new-data.firebasestorage.app',
    measurementId: 'G-WM2N72QYXJ',
  );
}
